### ISSUE TITLE
您好，请教一个NSP的问题， 多谢！

### ISSUE THREAD

**Issue by wangquent** [liulilittle/PaperAirplane#13]
在Install 我们自己DLL之后，通过DbgView可以看到Lookupnext函数里返回了虚拟IP。但是通过nslookup命令，并没有得到相应虚拟IP返回结果。
首先我是猜想可能是因为通过自己的NSP程序返回的虚拟IP优先级不高，但是当我取nslookup一个不存在解析的域名时，也并没有返回虚拟IP的结果而是直接返回不存在该域名的解析。。这让我百思不得其解
此外我也尝试了使用WSCEnable禁用系统原有的解析以及使用WSCWriteNameSpaceOrder函数调整NSP的优先级，也并没有什么收获。
所以想请教您在开发的过程中，是否有遇到过类似的问题呢？

**Comment by wangquent** [comment]
在注册表中检查了一下，发现有一点细节可能是导致问题的原因之一
我的电脑是64位的操作系统，调用没有指定32位的WSCInstallNameSpace、WSCEnableNSProvider等API，均生效在注册表的Catalog_Entries路径而非64位的Catalog_Entries路径下

**Comment by liulilittle** [comment]
对于x64的系统，你需要准备两个不同指令集平台的NSP/DLL；一个是x86，一个是x64同时你需要把这两个DLL放到系统对应的目录里面在注册。
1、x86放到 %windir%\SysWow64 文件夹之中
2、x64放到 %windir%\System32 文件夹之中

当然如果你仅仅只想要DNS污染的情况下你可以在本地计算机上，侦听localhost or local的53/UDP端口直接处理DNS协议的请求。在本地网卡上设置上你编写的虚拟DNS服务器，一样可以做到NSP能做到的事情，而且会比NSP更加可靠！

**Comment by wangquent** [comment]
> 对于x64的系统，你需要准备两个不同指令集平台的NSP/DLL；一个是x86，一个是x64同时你需要把这两个DLL放到系统对应的目录里面在注册。
> 1、x86放到 %windir%\SysWow64 文件夹之中
> 2、x64放到 %windir%\System32 文件夹之中
> 
> 当然如果你仅仅只想要DNS污染的情况下你可以在本地计算机上，侦听localhost or local的53/UDP端口直接处理DNS协议的请求。在本地网卡上设置上你编写的虚拟DNS服务器，一样可以做到NSP能做到的事情，而且会比NSP更加可靠！

我现在的实现也是这种方式类似。。不过看到Proxifier用的NSP，所以想研究一下。。。
目前看起来一切工作都正常了，但是当某个域名有解析但是我希望它使用Fake IP返回时，依然系统的解析优先级更高了，只有当我disable掉NS_DNS的provider时才能返回虚拟IP（甚至我把我们的Porvider的order排到最前也是这个效果）

**Comment by liulilittle** [comment]
PaperAirplane NSP这部分运行时一定会把自己顶到分层最上层有限处理的，有些进程无法载入与NSP没有特别大的关系，而是目标进程保护机制的问题。它会造成目标进程无法载入NSP/LSP的问题，这本身也是NSP/LSP这种类型的一个缺陷，容易被有心程序反抗而且只需要简简单单的inline-hook就可以解决，一般来说要解决这个问题必须要一个比较高级别的CA数字证书（例如沃通），让对方保护机制这块可以信任（但也可能不被信任，缺陷比较大），但是对于非商业团体用户而言其实意义不大，做游戏加速器或者大多数应用程序代理是没有特别大的问题的。

**Comment by liulilittle** [comment]
所以如果你想要整个计算机代理的话，可以参考 https://github.com/liulilittle/SkylakeNAT/ （TAP虚拟网卡方式）或许比较适合

**Comment by wangquent** [comment]
> PaperAirplane NSP这部分运行时一定会把自己顶到分层最上层有限处理的，有些进程无法载入与NSP没有特别大的关系，而是目标进程保护机制的问题。它会造成目标进程无法载入NSP/LSP的问题，这本身也是NSP/LSP这种类型的一个缺陷，容易被有心程序反抗而且只需要简简单单的inline-hook就可以解决，一般来说要解决这个问题必须要一个比较高级别的CA数字证书（例如沃通），让对方保护机制这块可以信任（但也可能不被信任，缺陷比较大），但是对于非商业团体用户而言其实意义不大，做游戏加速器或者大多数应用程序代理是没有特别大的问题的。

我看到nsp.cpp中，behavior的变量对整个流程的控制，想请教一下这个变量的意义

**Comment by liulilittle** [comment]
behavior 在NSP变量里面是表示会话层之上的应用层NSPLookup的操作状态，
NSP分了以下几个行为步骤
NSPLookupServiceBegin、NSPLookupServiceNext、NSPLookupServiceEnd ；

我们基于NSP层需要保证应用层操作正确性，否则mswsock可能会丢弃NSP 
FAR 返回的结果；
应用层不能跳过 Begin 就直接调用 End 同时每个behavior 标记状态需要处理对应事务逻辑。

**Comment by wangquent** [comment]
> behavior 在NSP变量里面是表示会话层之上的应用层NSPLookup的操作状态，
> NSP分了以下几个行为步骤
> NSPLookupServiceBegin、NSPLookupServiceNext、NSPLookupServiceEnd ；
> 
> 我们基于NSP层需要保证应用层操作正确性，否则mswsock可能会丢弃NSP
> FAR 返回的结果；
> 应用层不能跳过 Begin 就直接调用 End 同时每个behavior 标记状态需要处理对应事务逻辑。

了解了，多谢。。。研究了几天，为了避免干扰禁用了系统查询 发现有时uninstall了库之后，这个库还处于被应用占用的情况

**Comment by wangquent** [comment]
> behavior 在NSP变量里面是表示会话层之上的应用层NSPLookup的操作状态，
> NSP分了以下几个行为步骤
> NSPLookupServiceBegin、NSPLookupServiceNext、NSPLookupServiceEnd ；
> 
> 我们基于NSP层需要保证应用层操作正确性，否则mswsock可能会丢弃NSP
> FAR 返回的结果；
> 应用层不能跳过 Begin 就直接调用 End 同时每个behavior 标记状态需要处理对应事务逻辑。

了解了，多谢。研究了几天，我现在的处理是这样，在begin的时候就去尝试做DNS解析，如果解析不到结果，就可以在Begin的时候就设置标记把剩余全部流程都交给系统解析去做（这样在禁用系统解析的情况下，自己的解析失败通过系统解析获得结果）
不过目前感觉uninstall的时候，动态库经常被进程占据，删除不掉

**Comment by wangquent** [comment]
uninstall后  仍然有部分进程持有我们的nsp动态库  这个有遇到过吗。。。研究了几天也没发现原因，像是remove之后  一部分进程仍然在调用airplane.dll的方法没有结束

**Comment by liulilittle** [comment]
这是正确现象，除非这些进程主动卸载airplane.dll或者关闭进程；才可以释放对于airplane.dll的资源写权限。。一般都是在虚拟机内搞得，搞得比较稳定以后在移植到本地主机。

**Comment by wangquent** [comment]
> 这是正确现象，除非这些进程主动卸载airplane.dll或者关闭进程；才可以释放对于airplane.dll的资源写权限。。一般都是在虚拟机内搞得，搞得比较稳定以后在移植到本地主机。

对照了下proxifier，确实是这样，难怪proxider覆盖安装和卸载后都会要求重新启动。。。
完成了win7下的DNS本地解析（注册表disable掉msmsock.dll 和Prxf的win7方式一样），目前完美解决

win10下还是稍微有点蛋疼，disable掉msmsock.dll  edge就无法解析DNS了（怀疑强制指定了mswscok去解析）。。观察了下proxifier在win10上确实没有去disable掉msmsock.dll，但是这种情况下ping的结果又解决不了dns混淆问题（系统结果优先）。。。其他像chrome等浏览器均正常且能够解决dns混淆
真是好奇proxifier是如果解决这个问题的

**Comment by liulilittle** [comment]
解决这个问题的办法有很多；例如窗口句柄监视、内核事件同步对象、ICP/LCP（进程间过程调用 | 本地过程调用）都是可行的办法。
proxifier 解决这个问题办法与上面提点到方法是类似的，只要检测到没有启用的信号则NSP/LSP则不处理，把调用请求重定向到原始的mswsocks提供的链表指向的目标函数。

**Comment by wangquent** [comment]
> 解决这个问题的办法有很多；例如窗口句柄监视、内核事件同步对象、ICP/LCP（进程间过程调用 | 本地过程调用）都是可行的办法。
> proxifier 解决这个问题办法与上面提点到方法是类似的，只要检测到没有启用的信号则NSP/LSP则不处理，把调用请求重定向到原始的mswsocks提供的链表指向的目标函数。

你理解错我的意思啦，我的意思是在win10下采用和Proxifier一样的方式安装命名空间提供程序（Install和writeorder两步）， Chrome和qq浏览器一类使用32位的命名空间提供程序能够正常解决dns混淆问题， 自己的NSP解析结果能够在系统解析结果之上；但是系统的ping和自带的edge浏览器使用64位命名空间提供程序却不行，始终都是以系统解析结果优先。。。。着实头疼

**Comment by wangquent** [comment]
> > 解决这个问题的办法有很多；例如窗口句柄监视、内核事件同步对象、ICP/LCP（进程间过程调用 | 本地过程调用）都是可行的办法。
> > proxifier 解决这个问题办法与上面提点到方法是类似的，只要检测到没有启用的信号则NSP/LSP则不处理，把调用请求重定向到原始的mswsocks提供的链表指向的目标函数。
> 
> 你理解错我的意思啦，我的意思是在win10下采用和Proxifier一样的方式安装命名空间提供程序（Install和writeorder两步）， Chrome和qq浏览器一类使用32位的命名空间提供程序能够正常解决dns混淆问题， 自己的NSP解析结果能够在系统解析结果之上；但是系统的ping和自带的edge浏览器使用64位命名空间提供程序却不行，始终都是以系统解析结果优先。。。。着实头疼

最后发现  貌似因为UWP应用针对nsp的问题
